import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '../sass/globals.scss';
import { ContextProvider } from '@/contexts/app.context';
import { Header } from '@/components/Header/Header';
import { DropdownProvider } from '@/contexts/dropdown.context';

const poppins = Poppins({
	subsets: ['latin'],
	weight: ['400', '500', '600', '700', '800', '900'],
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Project Starter',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='pl'>
			<body className={poppins.className}>
				<ContextProvider>
					<DropdownProvider>
						<Header />
						{children}
					</DropdownProvider>
				</ContextProvider>
			</body>
		</html>
	);
}
